### ISSUE TITLE
As a question asker, I want to post a question so that I can get answers

### ISSUE THREAD

**Issue by rmdluo** [CMU-313/spring24-nodebb-team-garden#1]
Tasks:

- #4 
- #6

**Comment by aecai** [comment]
Given that NodeBB primarily functions as an interactive forum, this feature holds the top priority as it represents the fundamental step needed to initiate discussions. Enabling users to post questions is crucial for aligning with the platform's core functionality. It directly contributes to fostering engagement and facilitating the sharing of knowledge among community members.
