### ISSUE TITLE
add new extended markdown plugin to incorporate the ability to change text color

### ISSUE THREAD

**Issue by kdunkerl** [CMU-313/spring24-nodebb-team-garden#14]
reviewers: @alliefeld @aecai

**Comment by rmdluo** [comment]
Task: Install nodebb-plugin-extended-markdown and figure out how to make that install on build for other team members
Estimated effort: high
Dependencies: None
Acceptance Criteria:
- text color can be changed in markdown textarea to create a topic

**Comment by kdunkerl** [comment]
This does not have a pull request associated with it because the extended markdown plugin has been identified as a solution and been installed locally. A new issue #25 has been created for making sure the right files are modified so the extended markdown plugin is installed upon build after a new install.
